/**
 * Tailwind CSS Configuration
 * 
 * Custom configuration for Lalith's portfolio website featuring:
 * - Glassmorphism design system with custom colors
 * - Inter and Poppins font integration
 * - Custom spacing and screen breakpoints
 * - Production optimizations for smaller bundle size
 * 
 * @author Lalith
 * @version 1.0.0
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        poppins: ["Poppins", "sans-serif"],
      },
      colors: {
        primary: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
        glass: {
          light: "rgba(255, 255, 255, 0.1)",
          medium: "rgba(255, 255, 255, 0.2)",
          dark: "rgba(0, 0, 0, 0.1)",
        },
      },
      backdropBlur: {
        xs: "2px",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        glow: "glow 2s ease-in-out infinite alternate",
        typewriter: "typewriter 2s steps(40) forwards",
        blink: "blink 1s infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        glow: {
          from: { boxShadow: "0 0 20px rgba(14, 165, 233, 0.5)" },
          to: { boxShadow: "0 0 30px rgba(14, 165, 233, 0.8)" },
        },
        typewriter: {
          to: { left: "100%" },
        },
        blink: {
          "0%": { opacity: "0" },
          "50%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
      },
      // Add only the spacing values we actually use
      spacing: {
        18: "4.5rem",
        88: "22rem",
      },
      // Add only the screens we need
      screens: {
        xs: "475px",
      },
    },
  },
  plugins: [],
  // Optimize for production
  ...(process.env.NODE_ENV === "production" && {
    corePlugins: {
      // Disable unused core plugins for smaller bundle
      preflight: true,
      container: false,
      accessibility: true,
      alignContent: true,
      alignItems: true,
      alignSelf: true,
      animation: true,
      appearance: false,
      backdropBlur: true,
      backdropBrightness: false,
      backdropContrast: false,
      backdropGrayscale: false,
      backdropHueRotate: false,
      backdropInvert: false,
      backdropOpacity: true,
      backdropSaturate: false,
      backdropSepia: false,
      backgroundAttachment: false,
      backgroundClip: true,
      backgroundColor: true,
      backgroundImage: true,
      backgroundOpacity: true,
      backgroundPosition: true,
      backgroundRepeat: false,
      backgroundSize: true,
      blur: true,
      borderCollapse: false,
      borderColor: true,
      borderOpacity: true,
      borderRadius: true,
      borderStyle: true,
      borderWidth: true,
      boxShadow: true,
      boxSizing: true,
      brightness: false,
      clear: false,
      contrast: false,
      cursor: true,
      display: true,
      divideColor: false,
      divideOpacity: false,
      divideStyle: false,
      divideWidth: false,
      dropShadow: false,
      fill: false,
      filter: false,
      flex: true,
      flexDirection: true,
      flexGrow: true,
      flexShrink: true,
      flexWrap: true,
      float: false,
      fontFamily: true,
      fontSize: true,
      fontSmoothing: true,
      fontStyle: true,
      fontVariantNumeric: false,
      fontWeight: true,
      gap: true,
      gradientColorStops: true,
      grayscale: false,
      gridAutoColumns: false,
      gridAutoFlow: false,
      gridAutoRows: false,
      gridColumn: false,
      gridColumnEnd: false,
      gridColumnStart: false,
      gridRow: false,
      gridRowEnd: false,
      gridRowStart: false,
      gridTemplateColumns: true,
      gridTemplateRows: false,
      height: true,
      hueRotate: false,
      inset: true,
      invert: false,
      isolation: false,
      justifyContent: true,
      justifyItems: false,
      justifySelf: false,
      letterSpacing: true,
      lineHeight: true,
      listStylePosition: false,
      listStyleType: false,
      margin: true,
      maxHeight: true,
      maxWidth: true,
      minHeight: true,
      minWidth: true,
      mixBlendMode: false,
      objectFit: false,
      objectPosition: false,
      opacity: true,
      order: false,
      outline: true,
      overflow: true,
      overscrollBehavior: false,
      padding: true,
      placeContent: false,
      placeItems: false,
      placeSelf: false,
      placeholderColor: true,
      placeholderOpacity: true,
      pointerEvents: true,
      position: true,
      resize: true,
      ringColor: true,
      ringOffsetColor: true,
      ringOffsetWidth: true,
      ringOpacity: true,
      ringWidth: true,
      rotate: false,
      saturate: false,
      scale: false,
      sepia: false,
      skew: false,
      space: true,
      stroke: false,
      strokeWidth: false,
      tableLayout: false,
      textAlign: true,
      textColor: true,
      textDecoration: false,
      textDecorationColor: false,
      textDecorationStyle: false,
      textDecorationThickness: false,
      textIndent: false,
      textOpacity: true,
      textOverflow: false,
      textTransform: false,
      textUnderlineOffset: false,
      transform: true,
      transformOrigin: false,
      transitionDelay: false,
      transitionDuration: true,
      transitionProperty: true,
      transitionTimingFunction: true,
      translate: false,
      userSelect: false,
      verticalAlign: false,
      visibility: false,
      whitespace: false,
      width: true,
      wordBreak: false,
      zIndex: true,
    },
  }),
};
